{{- if and (not .Values.rpc.existingSecret) .Values.rpc.url }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "evm-stream.fullname" . }}-rpc
  labels:
    {{- include "evm-stream.labels" . | nindent 4 }}
type: Opaque
stringData:
  RPC_URL: {{ .Values.rpc.url | quote }}
{{- end }}
